### ISSUE TITLE
把输入法切换部分独立出来吧

### ISSUE THREAD

**Issue by Justsoos** [manateelazycat/hammerspoon-config#2]
目前在这里的：
https://emacs-china.org/t/topic/6348

首贴应该是你原始，还没 boost 过的code，不少人看这个贴直接用了code啊，下面回复的那些，都是本项目的代码了。

最好拆输入法切换的为单独的代码，方便后来者用，比如单独为一个 gist

另外，最好加上默认--非配置的 app 都使用 English 的判断。

**Comment by manateelazycat** [comment]
已经不用Mac了，感兴趣可以自己fork，这个项目就是我个人的配置，不是作为独立的编程项目。
